### ISSUE TITLE
checkpoint is not compatible with the network architecture

### ISSUE THREAD

**Issue by ZhengzxDev** [3dpose/3D-Multi-Person-Pose#24]
your model is perfectly satisfied with our requirements, but after several attempts, it seems that the checkpoint file that you provided is not compatible with the code. can you provide the latest pretrain-model?
![edc3a62d64d38b2373738aae6c66be77](https://github.com/3dpose/3D-Multi-Person-Pose/assets/56790096/25416532-f75d-42a2-9d32-29b2537c4caa)

**Comment by chojinie** [comment]
me too. how can i get pre-trained model?

**Comment by jpsml** [comment]
I am getting a similar error:

normal init for last conv 
Trying to load from: ./ckpts/model_btmup/
Traceback (most recent call last):
  File "calculate_mupots_btmup.py", line 30, in <module>
    M.Saver(model).restore('./ckpts/model_btmup/')
  File "/home/jpsml/anaconda3/envs/3dmpp/lib/python3.6/site-packages/TorchSUL/Model.py", line 156, in restore
    self.model.load_state_dict(state_dict, strict=strict)
  File "/home/jpsml/anaconda3/envs/3dmpp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1037, in load_state_dict
    load(self)
  File "/home/jpsml/anaconda3/envs/3dmpp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1035, in load
    load(child, prefix + name + '.')
  File "/home/jpsml/anaconda3/envs/3dmpp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1035, in load
    load(child, prefix + name + '.')
  File "/home/jpsml/anaconda3/envs/3dmpp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1035, in load
    load(child, prefix + name + '.')
  [Previous line repeated 1 more time]
  File "/home/jpsml/anaconda3/envs/3dmpp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1032, in load
    state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
  File "/home/jpsml/anaconda3/envs/3dmpp/lib/python3.6/site-packages/TorchSUL/Layers.py", line 106, in _load_from_state_dict
    raise Exception('No weight found for layer:', prefix)
Exception: ('No weight found for layer:', 'backbone.lastfuse.c_all.conv.')

**Comment by ddddwee1** [comment]
Please try to downgrade your TorchSUL to 0.1.28
